### PR TITLE
Update mfdread.py | Add Value Blocks color support

### PR DESCRIPTION
**Pull request by li0ard**
Add Value Blocks color support and display year of manufacture

### CODE REVIEW

**Comment by zhovner** [comment]
Thank you! Can you please leave spaces instead of changing it to tabs?

**Comment by li0ard** [comment]
Можно и на русском написать ;)

**Comment by li0ard** [comment]
Обновил, если я конечно правильно вас понял

**Comment by zhovner** [comment]
Aw sorry, I forget to merge. Can you please leave it?

**Pull request closed without merging**
