### PR TITLE
Support MiFare Classic Mini

### PR DESCRIPTION
**Pull request by anatolebeuzon**
Thanks for this great tool! :-)

This super short PR adds support for MiFare Classic Mini ([basically a MiFare classic with only 320 bytes of storage](https://en.wikipedia.org/wiki/MIFARE#MIFARE_Classic_family)).

### CODE REVIEW

**Comment by zhovner** [comment]
Can you please attach an example of such dump.

**Comment by oxlay** [comment]
Sure, here it is:

[sample-mifare-mini-dump.bin.zip](https://github.com/zhovner/mfdread/files/4064726/sample-mifare-mini-dump.bin.zip)

**Comment by anatolebeuzon** [comment]
Any thoughts on this?

**Comment by zhovner** [comment]
Sorry, miss it.

**Pull request merged**
